Notification/urls.py
from django.conf.urls import url
from Notification import views

app_name = 'Notification'

urlpatterns = [

    url(r'^Fac/(?P<fac_id>[0-9]+)/$' , views.FacHome , name="FacHome"),
]

Notification_system/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$' , TemplateView.as_view(template_name='index.html') , name="index"),
    url(r'accounts/', include('accounts.urls')),
    url(r'home/', include('Notification.urls')),
]

accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url( r'StuSignUp/$' , views.StuSignUpView , name="StuSignUp"),
    url( r'logout/$' , views.Proflogout, name="logout"),
    url( r'StuLogIn/$', views.StuLogInView , name="StuLogIn"),
    url( r'FacLogIn/$', views.FacLogInView , name="FacLogIn"),
    url( r'FacSignUp/$' , views.FacSignUpView , name="FacSignUp"),
]

Notification/models.py
from django.contrib.auth.models import User, Group
from django.db import models
from DepUpdate.models import course


class Notif(models.Model):

    title = models.CharField(max_length=100)
    datetime = models.DateTimeField(auto_now=True)
    uploaded_by = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=20)
    related_course = models.ForeignKey(course,on_delete=models.CASCADE)
    uploaded_for = models.ForeignKey(Group)

accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

branches = [
        ("aero", "Aerospace"),
        ("civil", "Civil"),
        ("cse", "Computer Science"),
        ("ece", "Electronics & Communication"),
        ("elec", "Electrical"),
        ("mech", "Mechanical"),
        ("meta", "Materials & Metallurgical"),
        ("prod", "Production & Industrial"),
    ]

class Student(models.Model):


    years = [
        ("1", 1),
        ("2", 2),
        ("3", 3),
        ("4", 4),
    ]

    Name = models.CharField(max_length=50)
    Student_ID = models.CharField(max_length=8, blank=False, unique=True)
    DOB = models.DateField(verbose_name="Date Of Birth" )
    Branch = models.CharField(max_length=4, choices=branches, default="aero")
    Year_Of_Study = models.CharField(max_length=1, choices=years, default="1")
    Address = models.CharField(max_length=300)
    Contact_Number = PhoneNumberField(blank=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE , default=None)

class Faculty(models.Model):

    designations = [  ("prof","Professor"),
                      ("asso" , "Associate Professor"),
                      ("assi" , "Assistant Professor"),
                      ("inst" , "Instructor")
    ]

    Name = models.CharField(max_length=50)
    Faculty_ID = models.CharField(max_length=8, blank=False, unique=True)
    Department =  models.CharField(max_length=4, choices=branches, default="aero")
    Contact_Number = PhoneNumberField(blank=False)
    Designation = models.CharField(max_length=4 , choices=designations , default="prof")
    Qualification = models.CharField(max_length=300)
    user = models.OneToOneField(User, on_delete=models.CASCADE , default=None)

Notification/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User, Group
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from accounts.models import Faculty


def is_member(user):
    return user.groups.filter(name='Faculty').exists()

@user_passes_test(is_member,login_url='/accounts/FacLogIn')
@login_required(login_url='/accounts/FacLogIn')
def FacHome(request , fac_id):
    user = get_object_or_404(User , pk=fac_id)
    object = Faculty.objects.get(user=user)
    print(user.groups.all())
    return render(request, 'Notification/FacHome.html' , { 'object': object , 'faculty':user})

templates/Notification/FacHome.html
{% extends 'baseFac.html' %}

{% block main %}

    <hr>
    <div class="container target">
        <div class="row">
            <div class="col-sm-10">
                 <h1 class="">{{ object.Name }}</h1>
                <br>
                <button type="button" class="btn btn-md btn-success">Schedule new notification</button>
                <button type="button" class="btn btn-md btn-primary">See Previous Notifications</button>
                <button type="button" class="btn btn-md btn-info">More</button>
                <br>

            </div>


          <div class="col-sm-2"><a href="" class="pull-right"><img title="profile image" class="img-circle img-responsive" src="https://outreachwebseo.com/wp-content/uploads/2016/07/blank-profile.png"></a>
            </div>
        </div>
      <br>
        <div class="row">
            <div class="col-sm-3">
                <!--left col-->
                <ul class="list-group">
                    <li class="list-group-item text-muted" contenteditable="false">Profile</li>
                    <li class="list-group-item text-right"><span class="pull-left"><strong class="">Faculty ID</strong></span>{{ object.Faculty_ID }}</li>
                    <li class="list-group-item text-right"><span class="pull-left"><strong class="">Department</strong></span>{{ object.get_Department_display }}</li>
                    <li class="list-group-item text-right"><span class="pull-left"><strong class="">Designation</strong></span>{{ object.get_Designation_display }}</li>
                </ul>
            </div>

            <!--/col-3-->
            <div class="col-sm-9" style="" contenteditable="false">
                <div class="panel panel-default">
                    <div class="panel-heading">Qualification</div>
                    <div class="panel-body">{{ object.Qualification }}</div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">Contact Number</div>
                    <div class="panel-body">{{ object.Contact_Number }}</div>
                </div>

               <div class="panel panel-default">
                    <div class="panel-heading">Email ID</div>
                    <div class="panel-body">{{ user.email }}</div>
               </div>
            </div>
    </div>
    </div>

{% endblock %}