Notification_system/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$' , TemplateView.as_view(template_name='index.html') , name="index"),
    url(r'accounts/', include('accounts.urls')),
    url(r'home/', include('Notification.urls')),
]

accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url( r'StuSignUp/$' , views.StuSignUpView , name="StuSignUp"),
    url( r'logout/$' , views.Proflogout, name="logout"),
    url( r'StuLogIn/$', views.StuLogInView , name="StuLogIn"),
    url( r'FacLogIn/$', views.FacLogInView , name="FacLogIn"),
    url( r'FacSignUp/$' , views.FacSignUpView , name="FacSignUp"),
]

templates/base.html
<!DOCTYPE html>
<html>

{% load static %}
{% load staticfiles %}

<style>
ul.social-network {
	list-style: none;
	display: inline;
	margin-left:0 !important;
	padding: 0;
}
ul.social-network li {
	display: inline;
	margin: 0 5px;
}


/* footer social icons */
.social-network a.icoRss:hover {
	background-color: #F56505;
}
.social-network a.icoFacebook:hover {
	background-color:#3B5998;
}
.social-network a.icoTwitter:hover {
	background-color:#33ccff;
}
.social-network a.icoGoogle:hover {
	background-color:#BD3518;
}
.social-network a.icoVimeo:hover {
	background-color:#0590B8;
}
.social-network a.icoLinkedin:hover {
	background-color:#007bb7;
}
.social-network a.icoRss:hover i, .social-network a.icoFacebook:hover i, .social-network a.icoTwitter:hover i,
.social-network a.icoGoogle:hover i, .social-network a.icoVimeo:hover i, .social-network a.icoLinkedin:hover i {
	color:#fff;
}
a.socialIcon:hover, .socialHoverClass {
	color:#44BCDD;
}

.social-circle li a {
	display:inline-block;
	position:relative;
	margin:0 auto 0 auto;
	-moz-border-radius:50%;
	-webkit-border-radius:50%;
	border-radius:50%;
	text-align:center;
	width: 50px;
	height: 50px;
	font-size:20px;
    background-color: #D3D3D3;
}
.social-circle li i {
	margin:0;
	line-height:50px;
	text-align: center;
}

.social-circle li a:hover i, .triggeredHover {
	-moz-transform: rotate(360deg);
	-webkit-transform: rotate(360deg);
	-ms--transform: rotate(360deg);
	transform: rotate(360deg);
	-webkit-transition: all 0.2s;
	-moz-transition: all 0.2s;
	-o-transition: all 0.2s;
	-ms-transition: all 0.2s;
	transition: all 0.2s;
}
.social-circle i {
	color: #fff;
	-webkit-transition: all 0.8s;
	-moz-transition: all 0.8s;
	-o-transition: all 0.8s;
	-ms-transition: all 0.8s;
	transition: all 0.8s;
}


</style>

<head>
	<title>{% block titile %} {% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="utf-8">


	<script type="application/x-javascript">
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>
	<link href="{% static 'accounts/css/bootstrap.css' %}" rel='stylesheet' type='text/css' />
	<link href="{% static 'accounts/css/style.css' %}" rel='stylesheet' type='text/css' />
	<link href="{% static 'accounts/css/font-awesome.css' %}" rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Merriweather+Sans:300,300i,400,400i,700,700i,800" rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Mallanna" rel="stylesheet">

    {% block style %} {% endblock %}
</head>

<body>


    <!-- Main Block -->
    <div class="top-bar_sub_w3layouts_agile">
		<h6>STAY CONNECTED <a href="#">Contact Us </a></h6>
        {% block header %}{% endblock %}
		<div class="clearfix"> </div>
	</div>

    {% block main %}

    {% endblock %}

	<!--footer-->
	<div class="contact-footer-w3layouts-agile">

		<div class="bottom-social-agileits-w3ls">
			<div class="container">
				<div class="col-md-8 botttom-nav-w3ls-agileits">
					<ul class="f_links col-md-4">
						<li>
							<a href="">Home</a>
						</li>
						<li>
							<a href="">About</a>
						</li>
						<li>
							<a href="">Services</a>
						</li>
						<li>
							<a href="">Courses</a>
						</li>
						<li>
							<a href="">Contact</a>
						</li>
					</ul>
					<ul class="f_links col-md-4">
						<li>
							<a href="">Topics</a>
						</li>
						<li>
							<a href="">Blog</a>
						</li>
						<li>
							<a href="">Careers</a>
						</li>
						<li>
							<a href="">Services</a>
						</li>

					</ul>
					<ul class="f_links thrd col-md-4">
						<li>
							<a href="">Topics</a>
						</li>
						<li>
							<a href="">Events</a>
						</li>
						<li>
							<a href="">Mobile App</a>
						</li>


					</ul>
					<div class="clearfix"></div>
				</div>
				<div class="col-md-4 social-icons-wthree">
					<h6>Connect with us</h6>
					 <ul class="social-network social-circle">
                        <li><a href="#" class="icoRss" title="Rss"><i class="fa fa-rss"></i></a></li>
                        <li><a href="https://www.facebook.com" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="https://www.twitter.com" class="icoTwitter" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#" class="icoGoogle" title="Google +"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
                    </ul>
				</div>
				<div class="clearfix"></div>


			</div>
		</div>
		<div class="copy-w3-agileits">
			<h2 class="footer-logo"><a href="index.html">E-notification <span>System</span></a></h2>
			<div class="clearfix"></div>
		</div>
	</div>
	<!--/footer -->


	<!-- js -->
	<script type="text/javascript" src="{% static 'accounts/js/jquery-2.2.3.min.js'%}"></script>
	<!-- //js -->
	<!--search-bar-->
	<script src="{% static 'accounts/js/main.js'%}"></script>
	<script src="{% static 'accounts/js/responsiveslides.min.js'%}"></script>
	<script>
		$(function () {
			$("#slider4").responsiveSlides({
				auto: true,
				pager: true,
				nav: true,
				speed: 1000,
				namespace: "callbacks",
				before: function () {
					$('.events').append("<li>before event fired.</li>");
				},
				after: function () {
					$('.events').append("<li>after event fired.</li>");
				}
			});
		});
	</script>
	<!--//search-bar-->
	<link rel="stylesheet" type="text/css" href="{% static 'accounts/css/easy-responsive-tabs.css'%} " />
	<script src="{% static 'accounts/js/easyResponsiveTabs.js'%}"></script>
	<!--Plug-in Initialisation-->
	<script type="text/javascript">
		$(document).ready(function () {

			//Vertical Tab
			$('#parentVerticalTab').easyResponsiveTabs({
				type: 'vertical', //Types: default, vertical, accordion
				width: 'auto', //auto or any width like 600px
				fit: true, // 100% fit in a container
				closed: 'accordion', // Start closed if in accordion view
				tabidentify: 'hor_1', // The tab groups identifier
				activate: function (event) { // Callback function if tab is switched
					var $tab = $(this);
					var $info = $('#nested-tabInfo2');
					var $name = $('span', $info);
					$name.text($tab.text());
					$info.show();
				}
			});
		});
	</script>
	<!--/script-->
	<!-- start-smoth-scrolling -->
	<script type="text/javascript" src="{% static 'accounts/js/move-top.js'%}"></script>
	<script type="text/javascript" src="{% static 'accounts/js/easing.js'%}"></script>
	<script type="text/javascript">
		jQuery(document).ready(function ($) {
			$(".scroll").click(function (event) {
				event.preventDefault();
				$('html,body').animate({
					scrollTop: $(this.hash).offset().top
				}, 900);
			});
		});
	</script>
	<!-- start-smoth-scrolling -->

	<script type="text/javascript">
		$(document).ready(function () {
			/*
									var defaults = {
							  			containerID: 'toTop', // fading element id
										containerHoverID: 'toTopHover', // fading element hover id
										scrollSpeed: 1200,
										easingType: 'linear'
							 		};
									*/

			$().UItoTop({
				easingType: 'easeOutQuart'
			});

		});
	</script>
	<a href="#" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
	<script type="text/javascript" src="{% static 'accounts/js/bootstrap-3.1.1.min.js' %}"></script>


</body>

</html>

templates/baseFac.html
<!DOCTYPE html>
<html>

{% load static %}
{% load staticfiles %}


<head>
	<title>{% block title %} {% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="utf-8">


	<script type="application/x-javascript">
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>
	<link href="{% static 'accounts/css/bootstrap.css' %}" rel='stylesheet' type='text/css' />
	<link href="{% static 'accounts/css/style.css' %}" rel='stylesheet' type='text/css' />
	<link href="{% static 'accounts/css/font-awesome.css' %}" rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Merriweather+Sans:300,300i,400,400i,700,700i,800" rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Mallanna" rel="stylesheet">

    {% block style %} {% endblock %}
</head>

<body>


    <!-- Main Block -->
    <div class="top-bar_sub_w3layouts_agile">
		<h6>STAY CONNECTED <a href="#">Contact Us </a></h6>
        {% block header %}{% endblock %}
		<div class="clearfix"> </div>
	</div>

    <!--Header-->

	<div class="header inner_banner" id="home">
		<!--/top-bar-->
		<div class="top-bar">
			<div class="header-nav-agileits">

				<nav class="navbar navbar-default">
					<!-- Brand and toggle get grouped for better mobile display -->
					<div class="navbar-header">
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
									<span class="sr-only">Toggle navigation</span>
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
								</button>
						<h1><a class="navbar-brand" href="index.html">E-Notification <span>System</span></a></h1>
					</div>
					<!-- Collect the nav links, forms, and other content for toggling -->
					<div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
						<nav>
							<ul class="top_nav">
								<li><a href="">Home</a></li>
								<li><a href="">About</a></li>
								<li><a href="">Contact</a></li>
                                <li><a href=""><strong>Log Out</strong></a></li>
							</ul>
						</nav>
					</div>
				</nav>

			</div>
		</div>
		<!--// banner-text -->
	</div>

	<div class="services-breadcrumb-w3ls-agile">
		<div class="inner_breadcrumb">

			<ul class="short">
				<li><a href="{% url 'index' %}">Home</a><span>|</span></li>
				<li>Student Registration</li>
			</ul>
		</div>
	</div>

    {% block main %}

    {% endblock %}

	<!--footer-->
	<div class="contact-footer-w3layouts-agile">

		<div class="bottom-social-agileits-w3ls">
			<div class="container">
				<div class="col-md-8 botttom-nav-w3ls-agileits">
					<ul class="f_links col-md-4">
						<li>
							<a href="">Home</a>
						</li>
						<li>
							<a href="">About</a>
						</li>
						<li>
							<a href="">Services</a>
						</li>
						<li>
							<a href="">Courses</a>
						</li>
						<li>
							<a href="">Contact</a>
						</li>
					</ul>
					<ul class="f_links col-md-4">
						<li>
							<a href="">Topics</a>
						</li>
						<li>
							<a href="">Blog</a>
						</li>
						<li>
							<a href="">Careers</a>
						</li>
						<li>
							<a href="">Services</a>
						</li>

					</ul>
					<ul class="f_links thrd col-md-4">
						<li>
							<a href="">Topics</a>
						</li>
						<li>
							<a href="">Events</a>
						</li>
						<li>
							<a href="">Mobile App</a>
						</li>


					</ul>
					<div class="clearfix"></div>
				</div>
				<div class="col-md-4 social-icons-wthree">
					<h6>Connect with us</h6>
					 <ul class="social-network social-circle">
                        <li><a href="#" class="icoRss" title="Rss"><i class="fa fa-rss"></i></a></li>
                        <li><a href="https://www.facebook.com" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="https://www.twitter.com" class="icoTwitter" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#" class="icoGoogle" title="Google +"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
                    </ul>
				</div>
				<div class="clearfix"></div>


			</div>
		</div>
		<div class="copy-w3-agileits">
			<h2 class="footer-logo"><a href="index.html">E-notification <span>System</span></a></h2>
			<div class="clearfix"></div>
		</div>
	</div>
	<!--/footer -->


	<!-- js -->
	<script type="text/javascript" src="{% static 'accounts/js/jquery-2.2.3.min.js'%}"></script>
	<!-- //js -->
	<!--search-bar-->
	<script src="{% static 'accounts/js/main.js'%}"></script>
	<script src="{% static 'accounts/js/responsiveslides.min.js'%}"></script>
	<script>
		$(function () {
			$("#slider4").responsiveSlides({
				auto: true,
				pager: true,
				nav: true,
				speed: 1000,
				namespace: "callbacks",
				before: function () {
					$('.events').append("<li>before event fired.</li>");
				},
				after: function () {
					$('.events').append("<li>after event fired.</li>");
				}
			});
		});
	</script>
	<!--//search-bar-->
	<link rel="stylesheet" type="text/css" href="{% static 'accounts/css/easy-responsive-tabs.css'%} " />
	<script src="{% static 'accounts/js/easyResponsiveTabs.js'%}"></script>
	<!--Plug-in Initialisation-->
	<script type="text/javascript">
		$(document).ready(function () {

			//Vertical Tab
			$('#parentVerticalTab').easyResponsiveTabs({
				type: 'vertical', //Types: default, vertical, accordion
				width: 'auto', //auto or any width like 600px
				fit: true, // 100% fit in a container
				closed: 'accordion', // Start closed if in accordion view
				tabidentify: 'hor_1', // The tab groups identifier
				activate: function (event) { // Callback function if tab is switched
					var $tab = $(this);
					var $info = $('#nested-tabInfo2');
					var $name = $('span', $info);
					$name.text($tab.text());
					$info.show();
				}
			});
		});
	</script>
	<!--/script-->
	<!-- start-smoth-scrolling -->
	<script type="text/javascript" src="{% static 'accounts/js/move-top.js'%}"></script>
	<script type="text/javascript" src="{% static 'accounts/js/easing.js'%}"></script>
	<script type="text/javascript">
		jQuery(document).ready(function ($) {
			$(".scroll").click(function (event) {
				event.preventDefault();
				$('html,body').animate({
					scrollTop: $(this.hash).offset().top
				}, 900);
			});
		});
	</script>
	<!-- start-smoth-scrolling -->

	<script type="text/javascript">
		$(document).ready(function () {
			/*
									var defaults = {
							  			containerID: 'toTop', // fading element id
										containerHoverID: 'toTopHover', // fading element hover id
										scrollSpeed: 1200,
										easingType: 'linear'
							 		};
									*/

			$().UItoTop({
				easingType: 'easeOutQuart'
			});

		});
	</script>
	<a href="#" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
	<script type="text/javascript" src="{% static 'accounts/js/bootstrap-3.1.1.min.js' %}"></script>


</body>

</html>

templates/index.html
{% extends 'base.html' %}

{% block main %}

<!--Header-->
	<div class="header" id="home">
		<!--/top-bar-->
		<div class="top-bar">
			<div class="header-nav-agileits">

				<nav class="navbar navbar-default">
					<!-- Brand and toggle get grouped for better mobile display -->
					<div class="navbar-header">
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
									<span class="sr-only">Toggle navigation</span>
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
								</button>
						<h1><a class="navbar-brand" href="index.html">E-Notification <span>System</span></a></h1>
					</div>
					<!-- Collect the nav links, forms, and other content for toggling -->
					<div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
						<nav>
							<ul class="top_nav">
								<li><a href="" class="active">Home</a></li>
								<li><a href="">About</a></li>
								<li class="dropdown">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="Pages" role="button" aria-haspopup="true" aria-expanded="false">Registration Section<span class="fa fa-angle-down"></span></a>
									<ul class="dropdown-menu">
										<li><a href="{% url 'accounts:StuSignUp' %}">Student</a></li>
										<li><a href="{% url 'accounts:FacSignUp' %}">Faculty</a></li>
									</ul>
								</li>

								<li class="dropdown">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="Pages" role="button" aria-haspopup="true" aria-expanded="false">Log-in Section<span class="fa fa-angle-down"></span></a>
									<ul class="dropdown-menu">
										<li><a href="{% url 'accounts:StuLogIn' %}">Student</a></li>
										<li><a href="{% url 'accounts:FacLogIn' %}">Faculty</a></li>
									</ul>
								</li>

								<li><a href="">Contact</a></li>
							</ul>
						</nav>
					</div>
				</nav>

			</div>
		</div>
		<!--// banner-text -->
	</div>
		<!--//top-bar-->
		<!-- banner-text -->
		<div class="slider">
			<div class="callbacks_container">
				<ul class="rslides callbacks callbacks1" id="slider4">
					<li>
						<div class="banner-top">
							<div class="banner-info-w3ls-agileinfo">
								<h3>Easy and Quick Services.</h3>

							</div>

						</div>
					</li>
					<li>
						<div class="banner-top1">
							<div class="banner-info-w3ls-agileinfo">
								<h3>Reduce Dependencies</h3>

							</div>

						</div>
					</li>
					<li>
						<div class="banner-top2">
							<div class="banner-info-w3ls-agileinfo">
								<h3>Connectify Yourself.</h3>

							</div>

						</div>
					</li>
					<li>
						<div class="banner-top3">
							<div class="banner-info-w3ls-agileinfo">
								<h3>Education is a path, not a destination</h3>

							</div>

						</div>
					</li>
				</ul>
			</div>
			<div class="clearfix"> </div>

			<!--banner Slider starts Here-->
		</div>
		<!--//Slider-->

	<!--/what-wedo-->
	<div class="top_spl_courses">
		<div class="container">
			<h3 class="headerw3">3 Different Layouts</h3>
			<div class="inner_sec_w3_agileinfo">

				<div class="col-md-6 edu-left">
					<h4 class="sub-hdng two">For Your Digital Life</h4>
					<p class="paragraph">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam,
						eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
					<p class="paragraph two">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam,
						eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>

				</div>
				<div class="col-md-6 edu_img">
					<img src="images/stretch.jpg" alt=" " class="img-responsive">
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!--/what-wedo-->


	<div class="services">
		<div class="container">
			<h3 class="headerw3">Featured Courses</h3>
			<div class="inner_sec_w3_agileinfo">
				<div class="col-md-4 grid_info_main">
					<div class="grid_info">
						<div class="icon_info">
							<span class="fa fa-line-chart" aria-hidden="true"></span>
							<h5>Financial Analyst Course</h5>
							<p>Lorem ipsum dolor sit amet,vehicula vel sapien et, feugiat sapien amet.</p>
						</div>
					</div>
					<div class="grid_info second">
						<div class="icon_info">
							<span class="fa fa-bookmark" aria-hidden="true"></span>
							<h5>Discipline</h5>
							<p>Lorem ipsum dolor sit amet,vehicula vel sapien et, feugiat sapien amet.</p>
						</div>
					</div>
				</div>
				<div class="col-md-4 grid_info_main">
					<div class="grid_info">
						<div class="icon_info">
							<span class="fa fa-bicycle" aria-hidden="true"></span>
							<h5>Sport Exercise Sciences</h5>
							<p>Lorem ipsum dolor sit amet,vehicula vel sapien et, feugiat sapien amet.</p>
						</div>
					</div>
					<div class="grid_info second">
						<div class="icon_info">
							<span class="fa fa-female" aria-hidden="true"></span>
							<h5>Life style</h5>
							<p>Lorem ipsum dolor sit amet,vehicula vel sapien et, feugiat sapien amet.</p>
						</div>
					</div>
				</div>
				<div class="col-md-4 grid_info_main">
					<div class="grid_info">
						<div class="icon_info">
							<span class="fa fa-laptop" aria-hidden="true"></span>
							<h5>It and Software</h5>
							<p>Lorem ipsum dolor sit amet,vehicula vel sapien et, feugiat sapien amet.</p>
						</div>
					</div>
					<div class="grid_info second">
						<div class="icon_info">
							<span class="fa fa-home" aria-hidden="true"></span>
							<h5>Interior Design</h5>
							<p>Lorem ipsum dolor sit amet,vehicula vel sapien et, feugiat sapien amet.</p>
						</div>
					</div>
				</div>

				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!--//services-->
	<!--/top_spl_courses-->

	<div class="top_spl_courses">
		<div class="container">
			<h3 class="headerw3">How it works</h3>
			<div class="inner_sec_w3_agileinfo">
				<div class="tabs-grids">
					<div id="parentVerticalTab">
						<ul class="resp-tabs-list hor_1">
							<li>Coursework</li>
							<li>Help & Support</li>
							<li>Certificates</li>


						</ul>
						<div class="resp-tabs-container hor_1">
							<div class="text-info">
								<h4>Coursework</h4>
								<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accUKntium doloremque laudantium, totam rem aperiam,
									eaque ipsa quae ab illo inventore veritatis et quasi architecto.</p>
								<p class="sec">Consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat
									voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid
									ex ea commodi consequatur.</p>
								<img src="images/banner1.jpg" alt=" " class="img-responsive" />

							</div>
							<div class="text-info">
								<h4>Help & Support</h4>
								<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accUKntium doloremque laudantium, totam rem aperiam,
									eaque ipsa quae ab illo inventore veritatis et quasi architecto.</p>
								<p class="sec">Consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat
									voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid
									ex ea commodi consequatur.</p>
								<img src="images/banner2.jpg" alt=" " class="img-responsive" />

							</div>

							<div class="text-info">
								<h4>Certificates</h4>
								<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accUKntium doloremque laudantium, totam rem aperiam,
									eaque ipsa quae ab illo inventore veritatis et quasi architecto.</p>
								<p class="sec">Consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat
									voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid
									ex ea commodi consequatur.</p>
								<img src="images/banner3.jpg" alt=" " class="img-responsive" />

							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!--//what-we-do-->

{% endblock %}